stages:
  - build
build_all:
  script:
    - make
  tags:
    - latex
  stage: build
  artifacts:
      paths:
      - AlgKT_SS16/algebraische_KTheorie.pdf
      - Ana1_WS12/analysis1.pdf
      - Ana2_SS13/analysis2.pdf
      - Ana2_SS15/Ana2.pdf
      - Ana3_WS13/analysis3.pdf
      - AnaTopGeo_SS14/ana_top_geo.pdf
      - CAT0_WS15/CAT0.pdf
      - DiffGeo_WS14/diff_geo.pdf
      - DiffMa_SS14/diff_ma.pdf
      - EinfAlg_WS13/algebra.pdf
      - EinfAlg_WS14/Einf_Algebra.pdf
      - EKK_SS15/EKK.pdf
      - EZT_WS14/EZT.pdf
      - Fima_WS14/Fima_WS14.pdf
      - FunkAna_WS14/funktional_analysis.pdf
      - HoehAlg1_SS14/hoehere_algebra.pdf
      - KTheorie_SS15/K-Theorie.pdf
      - LA1_WS12/lineare_algebra1.pdf
      - LA2_SS13/lineare_algebra2.pdf
      - LA2_SS16/LA2.pdf
      - LieGrp_SS16/liegruppen.pdf
      - ModRed_WS15/Modellreduktion.pdf
      - MadsenW_WS16/madsen_weiss.pdf
      - OpAlg_WS15/operatoralgebren.pdf
      - OpAlg2_SS16/operatoralgebren2.pdf
      - PDGL1_SS14/PDGL1.pdf
      - PDGL1_SS16/pdeskript.pdf
      - Topo1_WS14/topologie_1.pdf
      - Topo2_WS15/topologie_2.pdf
      - WTGraph_SS16/WTG.pdf
      - ZZT_SS17/ZZT_SS17.pdf

# cache all auxilliary files to speed up compilation
cache:
  untracked: true
  key: "$CI_BUILD_NAME"
