sudo: required

language: go

services:
  - docker

before_install:
  - sudo docker build -t texlive \!deploy
  - go get github.com/aktau/github-release

install: true

  
script:
  - make build
  - sudo chown -R $USER *
  
branches:
  except:
    - /^untagged-.*/
    - /^latest/
    
after_success:
  - git config user.name "Travis CI"
  - git config user.email "j.bantje@wwu.de"
  - GITHUB_TOKEN=$GH_TOKEN
  - github-release --help
  - github-release delete --user JaMeZ-B --repo LaTeX-WWU --tag latest
  - git push --delete "https://${GH_TOKEN}@${GH_REF}" latest
  - git tag -af latest -m "aktuelle Version aller Skripte"
  - git push --force --tags "https://${GH_TOKEN}@${GH_REF}"

deploy:
  provider: releases
  api_key:
    secure: MI+6zovtYldasrA1y+iC4YHKeXOvfEPCLnExY9ix3gxSAY6akQjNcEItwyhhlyV7WtxsSza08sOzDg+LPHMHmr8CrW2K7H1DjGoQLOyBr8vVWXQ9ubTmb6YOix4KeT/l8VmxHgsHAyjMps9PZEphopxRjzb4YSGqgTEUnWNLqnJDP43ldePoZO8BpUiJNOv5oQj3gSO+xbIIkHBjVfoxL4nLYah21hgO8BtE/Q22OMQaY9c7TtMwi6yN6YmyxJJiZNSXmYa9rjGeJtP3YhWvhOl6GAFlfzlz9NACuzIZStSpO/2hNXKs5MExshsU9Y6arLRPSOqqJnzJ/CfVOC1LwWjUgWssFJ+00rOy9I+6F03BzZLhAPOjXPWJlaWNSTHpHWlHOwG9nzVUC/iXnfEElmrduugadwfrkq3mPfIbg2uNOFT9cfepqB/Iv75QiDCgjqorzY8v0XyG95i/H2oilDRIJI0heT7mVamQ0DgX/hrUum0IEKw7K2x4FgOzH1OW4iKJwGMH2OoR4AHNn+0iAyPOHh1oBcaB5H3xzG/NRDRGWcrQqq9zPItcC611FSCtGoJwBVk/86niUIjW5oy6CTJ8vHHurgmzpxwRN+hdi2uSg9dHyEN1ZyrQXmP6h23lWLxPJijXDW3GqtEHJSgjXDsrwyd+wiDIzNAXC/gJuic=
  file:
    - AlgKT_SS16/algebraische_KTheorie.pdf
    - Ana1_WS12/analysis1.pdf
    - Ana2_SS13/analysis2.pdf
    - Ana2_SS15/Ana2.pdf
    - Ana3_WS13/analysis3.pdf
    - AnaTopGeo_SS14/ana_top_geo.pdf
    - CAT0_WS15/CAT0.pdf
    - DiffGeo_WS14/diff_geo.pdf
    - DiffMa_SS14/diff_ma.pdf
    - EinfAlg_WS13/algebra.pdf
    - EinfAlg_WS14/Einf_Algebra.pdf
    - EKK_SS15/EKK.pdf
    - EZT_WS14/EZT.pdf
    - Fima_WS14/Fima_WS14.pdf
    - FunkAna_WS14/funktional_analysis.pdf
    - HoehAlg1_SS14/hoehere_algebra.pdf
    - KTheorie_SS15/K-Theorie.pdf
    - LA1_WS12/lineare_algebra1.pdf
    - LA2_SS13/lineare_algebra2.pdf
    - LA2_SS16/LA2.pdf
    - LieGrp_SS16/liegruppen.pdf
    - ModRed_WS15/Modellreduktion.pdf
    - OpAlg_WS15/operatoralgebren.pdf
    - OpAlg2_SS16/operatoralgebren2.pdf
    - PDGL1_SS14/PDGL1.pdf
    - Topo1_WS14/topologie_1.pdf
    - Topo2_WS15/topologie_2.pdf
  skip_cleanup: true
  on:
    repo: JaMeZ-B/LaTeX-WWU
env:
  global:
  - GH_REF: github.com/JaMeZ-B/LaTeX-WWU.git
  - secure: E3TwBW3CW9xSmW4VhXgFSPDNPt2GDxN2ZW+BnlBGo7mHTJW/CjVUEY0zea0/L8okJ6AcpiPjXlbmGnnnpZQhRC33RZVUVfaQifqqQkgBNJ+vE8NOtFMit3VHLUGHowQ5hvN3qi43YhzY8CXFDi1wkFp/TuUcKtDA6XQexywAal7yKexuPXP8iRwVAYb1amuHv5wyqk9pEGnJdReNG+1bT6gPLQfZCpmRUJY9hDapkdd/+ZNe7/7FppS7M7ij/jd2lBIyl0KjPxHkR+5WjODwcDnXATZDS6MBIWsgOaaENB5QRI59bm2SEgK3MrEw4cVf9qk67oudbzDXxIvzaieDh3f8VDEzF2DsA5S2Ns2+C6PNGTSfwWmEukgGWV9sMiQUOa4bqlZJy+pChJQnecP5oaORtPtmhXsLgjgsfgUdNk6oCGkgZt7O+IUzp65NZ7B+goVDOHiIbY1Tf/zpxzlTU34OnXXuVdiXnOmPAmjW8z7jJoGcylQ0XOAG1WOner385Zr7kMXcNLr+lythkc6jlyJShXzQxKgC5Cw2PopF2iaWzwW8X4uBRWS9RwGe1fA8HD4s465+IVKMIozev3duCvjZPCFaK/akEY7fdXhCj4KdmDiTzFdRZOStsnGA51i68QthSKxDQH1JAUZgZ8OeHhBMpxGIqzWO8DSsth3SfuQ=
